import Pilha
P = Pilha.inicPilha()
print(P)
print(Pilha.Pilhavazia(P))
Pilha.push(P, "a")
print(P)
print(Pilha.PilhaCheia(P))
Pilha.push(P, "b")
print(P)
Pilha.push(P, "c")
print(P)
print(Pilha.pop(P))
print(P)
print(Pilha.pop(P))
print(P)
Pilha.push(P, "d")
print(P)
Pilha.push(P, "e")
print(P)
print(Pilha.top(P))
print(P)
print(Pilha.pop(P))
print(P)
print(Pilha.pop(P))
print(P)
